name: "CustoPiZe"

on:
  repository_dispatch:
    types: [octopi_release, octoprint_release]
  workflow_dispatch:
    inputs:
      octopi_version:
        description: "OctoPi version (leave empty to use latest stable release)"
        required: false
        default: ''
      octoprint_version:
        description: "OctoPrint version (leave empty to use latest stable release)"
        required: false
        default: ''

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    outputs:
      octoprint-version: ${{ env.OCTOPRINT_VERSION }}
      octopi-version: ${{ env.OCTOPI_VERSION }}
      tag: ${{ env.RELEASE_TAG }}
      image-zip: ${{ env.IMAGE_ZIP }}
      image-url: ${{ env.IMAGE_URL }}
    steps:

    - name: "⬇ Checkout"
      uses: actions/checkout@v4

    - name: "🔎 Determine OctoPi version"
      uses: actions/github-script@v6
      with:
        script: |
          let release = null;

          let version = '';
          if (context.eventName === "respository_dispatch" && context.action === "octopi_release") {
            version = context.payload.client_payload.version;
            console.log(`Version from repository dispatch: ${version}`);
          } else if (context.eventName === "workflow_dispatch") {
            version = context.payload.inputs.octopi_version;
            console.log(`Version from workflow dispatch: ${version}`);
          }

          if (version) {
            console.log(`Fetching release of ${version}`);

            const query = `query {
              repository(owner: "guysoft", name: "Octopi") {
                release(tagName:"${version}") {
                  tagName
                  releaseAssets(first:5) {
                    nodes {
                      name
                      downloadUrl
                    }
                  }
                }
              }
            }`;

            const result = await github.graphql(query);
            console.log({result});

            release = result.repository.release;

          } else {
            console.log("Fetching latest release");

            const query = `query {
              repository(owner:"guysoft", name:"OctoPi") {
                latestRelease {
                  tagName
                  releaseAssets(first:5) {
                    nodes {
                      name
                      downloadUrl
                    }
                  }
                }
              }
            }`;

            const result = await github.graphql(query);
            console.log({result});

            release = result.repository.latestRelease;
          }

          if (!release || !release.tagName || !release.releaseAssets || !release.releaseAssets.nodes) core.setFailed("Could not find OctoPi release");

          const octopiVersion = release.tagName;

          let octopiUrl = null;
          for (const asset of release.releaseAssets.nodes) {
            if (asset.name.startsWith("octopi-") && asset.name.includes("-armhf-") && asset.name.endsWith(".zip")) {
              octopiUrl = asset.downloadUrl;
              break;
            }
          }

          if (!octopiUrl) core.setFailed("Could not find OctoPi download URL");

          console.log(`OctoPi version: ${octopiVersion}`)
          console.log(`OctoPi download URL: ${octopiUrl}`)

          core.exportVariable("OCTOPI_VERSION", octopiVersion)
          core.exportVariable("OCTOPI_URL", octopiUrl)

    - name: "🔎 Determine OctoPrint version"
      run: |
        if [[ "${{ github.event_name }}" = "repository_dispatch" && "${{ github.event.action }}" = "octoprint_release" ]]; then
          OCTOPRINT_VERSION="${{ github.event.client_payload.version }}"
          echo "Version from repository dispatch: $OCTOPRINT_VERSION"
        else
          OCTOPRINT_VERSION="${{ github.event.inputs.octoprint_version }}"
          echo "Version from workflow dispatch: $OCTOPRINT_VERSION"
        fi

        if [ -z "$OCTOPRINT_VERSION" ]; then
          OCTOPRINT_VERSION=$(curl https://pypi.org/pypi/OctoPrint/json -s | jq -r '.info.version')
          echo "Version from PyPI: $OCTOPRINT_VERSION"
        fi

        # Make sure we have a published version
        curl -fsSL --output /dev/null --head https://pypi.org/pypi/OctoPrint/$OCTOPRINT_VERSION/ || exit 1

        echo "OctoPrint version: $OCTOPRINT_VERSION"

        echo "OCTOPRINT_VERSION=$OCTOPRINT_VERSION" >> $GITHUB_ENV

    - name: "⬇ Download OctoPi"
      id: octopi_download
      run: |
        mkdir build
        cd build
        curl -L -o octopi.zip https://github.com/guysoft/OctoPi/releases/download/1.0.0/octopi-bullseye-arm64-lite-1.0.0.zip

        unzip octopi.zip
        rm octopi.zip

        IMAGE=$(ls *.img | head -n 1)
        mv $IMAGE input.img

    - name: "🏗 Run CustoPiZer"
      run: |
        sudo modprobe loop
        docker run --rm --privileged \
          -e OCTOPRINT_VERSION=${{ env.OCTOPRINT_VERSION }} \
          -v ${{ github.workspace }}/scripts/files/config.local:/CustoPiZer/config.local \
          -v ${{ github.workspace }}/build:/CustoPiZer/workspace \
          -v ${{ github.workspace }}/scripts:/CustoPiZer/workspace/scripts \
          ghcr.io/octoprint/custopizer:latest

    - name: "✏ Rename image"
      run: |
        RELEASE_TAG="${{ env.RELEASE_TAG }}"

        IMAGE="octopi-$RELEASE_TAG.img"
        echo "IMAGE=$IMAGE" >> $GITHUB_ENV

        cd build
        mv output.img $IMAGE

    - name: "📦 Package the image"
      id: package-image
      uses: OctoPrint/actions/package-rpi-image@main
      with:
        image_path: "build/${{ env.IMAGE }}"

    - name: 📨 Export zip name and URL to env
      run: |
        echo "IMAGE_ZIP=${{ steps.package-image.outputs.zip_name }}" >> $GITHUB_ENV
        echo "IMAGE_URL=https://github.com/OctoPrint/OctoPi-UpToDate/releases/download/${{ env.RELEASE_TAG }}/${{ steps.package-image.outputs.zip_name }}" >> $GITHUB_ENV

    - name: "📝 Prepare release"
      run: |
        RELEASE_NAME="OctoPrint ${{ env.OCTOPRINT_VERSION }} (based on OctoPi ${{ steps.octopi_latestrelease.outputs.release }})"
        echo "RELEASE_NAME=$RELEASE_NAME" >> $GITHUB_ENV

        RELEASE_TAG="${{ env.OCTOPRINT_VERSION }}"
        echo "RELEASE_TAG=$RELEASE_TAG" >> $GITHUB_ENV

        RELEASE_BODY=""
        (git rev-parse $RELEASE_TAG >/dev/null 2>&1) || RELEASE_BODY="Created with [CustoPiZer](https://github.com/OctoPrint/CustoPiZer)"

        echo "RELEASE_BODY=$RELEASE_BODY" >> $GITHUB_ENV

    - name: "🔖 Create release & attach assets"
      uses: softprops/action-gh-release@v1
      with:
        name: "${{ env.RELEASE_NAME }}"
        tag_name: "${{ env.RELEASE_TAG }}"
        body: "${{ env.RELEASE_BODY }}"
        prerelease: ${{ contains(env.OCTOPRINT_VERSION, 'rc') }}
        fail_on_unmatched_files: true
        files: |
          build/${{ env.IMAGE }}.zip
          build/${{ env.IMAGE }}.zip.md5
          build/${{ env.IMAGE }}.zip.sha256
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}